### ISSUE TITLE
Предложения к исправлению от AlekVolsk

### ISSUE THREAD

**Issue by AlekVolsk** [Quantum-Manager/quantummanager#13]
**1. Работа под виндой**
В файле /administrator/components/com_quantummanager/helpers/quantummanager.php, строка 186, поправить так:
```php
if(!preg_match("/^" . str_replace("/", "\/", "("  . JPATH_ROOT  . DIRECTORY_SEPARATOR . "\)?" . $pathConfig) .".*?/", $path))
```
это позволит исправить баг под виндовыми серверами

**2. Отображение списков**
Основной контейнер менеджера перекрывается футером в 50px, что приводит к невозможности увидеть некоторые элементы в дереве папок и в списке файлов в табличном режиме

**3. Табличный вид**
В таблице хочется видеть дату и размер файла, для картинок и видео - размер,для видео и аудио - продолжительность (или хотя бы размер для картинок, на первое время). Сейчас это просто список, а не таблица.

**4. Переименовать режимы отображения**
Сеткой => Плитка (про сетку не разработчикам непонятно, и в именительном падеже)
Таблицей => Таблица (в именительном падеже)

**5. Выделение нескольких файлов**
При выделении нескольких файлов кнопка редактирования не должна быть видна либо должно быть реализовано какое-либо пакетное действие над файлами общего типа

**6. Видимость директорий и файлов**
Файлы с зарезервированными именами, такими как `index.html`, не должно быть видно в списке.
Файлы и папки, имеющие файловый атрибут "скрытый", или начинающиеся на символ нижнего подчёркивания или знак вопроса, должны отображаться только при включении соответствующей настройки отображения скрытых файлов и папок, их имена отображаться при этом более "серым" цветом

**7. Загрузка нескольких файлов одновременно**
Дропнуть сразу 5 файлов картинок - и чтобы все 5 сразу загрузились ("прошка" это умеет)

**Comment by AlekVolsk** [comment]
**8. Перемещение/копирование файлов внутри сервера**
Из файловой панели перетаскивать в папку в дереве выделенные файлы/папки для их перемещения, с нажатым контролом - копирования

**Comment by dmitriitux** [comment]
1 - винду починил
3 - уже выводе больше, появилось время, размер файла, доступ к записи
7 - сделано

**Comment by dmitriitux** [comment]
4. Названия ушли, остались только иконки, сетка так же научилась несколько плиток поддерживать и выбирать можно будет в выпадающем списке.
5. Выделение починил, появились так же новые действия.
6. Считать файл index.html я думаю не стоит, а вот сделать показ/скрытие скрытых объектов в будущем добавлю.
8. Перемещение расширю потом, в 1.5.0 появится возможность выделить папки вместе с файлами и их копировать/вырезать. Выделяешь, вырезаешь, переходишь в нужную папку и вставляешь.
Я закрываю issue, вроде бы в данном списке все решил важное. Остальное что осталось будет потихоньку добавлю.

**Comment by dmitriitux** [comment]
@AlekVolsk и винду в 1.5.0 снова починил :)
