### ISSUE TITLE
Ограничение пользователя по папке

### ISSUE THREAD

**Issue by kernusr** [Quantum-Manager/quantummanager#29]
У медиа-полей есть параметр directory (https://docs.joomla.org/Media_form_field_type), который может запереть пользователя в конкретной папке. На данный момент, квантумменеджер полностью игнорирует это поле, а так же некорректно отрабатывает, если в поле уже есть данные.

Ниже я нарисовал небольшую схему, как должен работать квантумменеджер, чтобы оставить логику областей, но учесть логику "запирания" пользователя в папке

https://drive.google.com/file/d/1VjJcGfBLnwls5MLBGETpPt6SN-U88l6_/view?usp=sharing

**Comment by kernusr** [comment]
Что-то разрешение у документа "не очень" получилось. Вот схема картинкой
![Untitled Diagram](https://user-images.githubusercontent.com/16020878/68529357-d703d700-030e-11ea-9fe6-39bd50659664.png)

**Comment by dmitriitux** [comment]
Это сложное решение, я по другому реализовал, описал в другом issue. Я закрою, если что из архивов потом достанем (этот issue) если потребуется.
