### ISSUE TITLE
Проблемы с запиранием в "Директории поля"

### ISSUE THREAD

**Issue by kernusr** [Quantum-Manager/quantummanager#30]
Если в медиа-поле выбрать файл и сохранить материал, то, при следующем открытии менеджера, мы оказываемся в "Директории поля" - папке, в которой лежит выбранный файл, и у нас нет возможности перейти в другую папку.
Чтобы эта возможность появилась, нужно нажать на крестик (очистка поля), сохранить материал и повторно открыть менеджер. Это явный баг!
Если реализовать работу с папками, как я описал в https://github.com/Delo-Design/quantummanager/issues/29 , то данного бага быть не должно

**Comment by dmitriitux** [comment]
Сделал по другому. Выгружается и активная сразу область "Директория поля", но выгружаются теперь все доступные области и можно переключиться на них.
Исправление будет в 1.5.0
