### ISSUE TITLE
"Open in a new window" doesn't work on subfolder

### ISSUE THREAD

**Issue by b2z** [Quantum-Manager/quantummanager#31]
https://www.norrnext.com/forum/quantum-manager/865-open-in-a-new-window-doesn-t-work

The left top button "Open in a new window" doesn't work here - it tries to open with url

`tld.com/administrator/index.php?option=com_quantummanager&layout=window&tmpl=component`

But joomla is installed here on tld.com/cms/ - so the correct url must be

`tld.com/cms/administrator/index.php?option=com_quantummanager&layout=window&tmpl=component`

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanager/commit/860317d4230e90399188a5e03895e7d692e17d4d
