### ISSUE TITLE
Pixabay. Параметр выбора размера картинки

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/quantummanager#39]
1. добавить возможность выбора размера. в pixabay есть разные размеры: 640, 1280, 1920 и большие. по умолчанию вытягивает большие картинки. неудобно. я обычно скачиваю какой-то нужный мне размер. если технически API позволяет выбрать размер, то нужно добавить такой параметр.

2. когда снова  нажимаю на pixabay, то нужно поисковый запрос заново набирать и ждать загрузку. предлагаю держать поледний запрос в памяти, чтобы сэкономить время

**Comment by dmitriitux** [comment]
Выбор размера добавил.
https://github.com/Quantum-Manager/quantummanager/commit/7bb5cec11e4aae1c9394d61e40b2c24747228837

**Comment by dmitriitux** [comment]
2. Сделал. А так же в unsplash сделал подобное поведение.
https://github.com/Quantum-Manager/quantummanager/commit/573523fb0335cf681203abf253fdcfbccb3e0d8c
